# Dockerfile for matchmaker service (lobby)
#  $ docker build -f './Dockerfile-lobby' -t markcornwell/spacewar-lobby:1 .
#  $ docker run -p 4999:4999 -d markcornwell/spacewar-lobby:1
#  $ . tests/lobby.sh

FROM node:13

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4999

CMD [ "npm", "run", "lobby"]
